"use client"; // Add this if you need to use client components/hooks here

import './globals.css';
import { AuthProvider } from '../Components/AuthContext';
import Navigation from '../Components/Navigation/Navigations';
import ProtectedRoute from '../Components/ProtectedRoute';
import styles from './layout.module.css';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <main className={styles.main}>
            <Navigation />
            <ProtectedRoute>
              {children}
            </ProtectedRoute>
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
